export const ProfileData = [
  {
    name: "ASSABAR Taoufik",
    spec: "Data Scientist",
    cv: "https://drive.google.com/open?id=1OR67MqPnbLsJ4ZipTBUahfjdUN0YXGqR",
    portfolio: "",
    img: "/images/TAOUFIK.jpeg",
  },
  {
    name: "EL EDRISSI Nassima",
    spec: "Data Scientist",
    cv: "https://drive.google.com/open?id=1PfGBY9qopI0Prh9tk9gutqiDWnmJ8871",
    portfolio: "https://nazele.github.io/portfolio/",
    img: "/images/Nassima.png",
  },
  {
    name: "NEJJARI Amal",
    spec: "Data Scientist",
    cv: "https://drive.google.com/open?id=1fHNqiqr_bxGDWbaDg5LbOcdYHGt3yQ0B",
    portfolio: "https://nejjari02.my.canva.site/",
    img: "/images/nejari.jpg",
  },
  {
    name: "BAKKAS soufiane",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=1hfvRb2IJ2OBlWFpdlNmhPUg4I_UAFdfm",
    portfolio: "https://bakkassoufian.github.io/Soufiane_bakkas.github.io/",
    img: "/images/Soufiane.jpg",
  },
  {
    name: "SGHIR nissrine",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=1REBkAtlNjGXwcNu7CdkJwZxNktNkShEN",
    portfolio: "https://nissrinesg.my.canva.site/",
    img: "/images/nissrine.jpg",
  },
  {
    name: "CHOUBRI Malika",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=13JN-katk6l0U6bs80WxqWlTFSNBQwwXO",
    portfolio:
      "https://drive.google.com/drive/folders/1d8i7zPx0hBdJR6mo9OcFzARRqN9HX49X?usp=sharing",
    img: "/images/malika.jpg",
  },
  {
    name: "TOUHAMI Ismail Aoulad",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=1_-hYLcr7Nv83NCPDdQFt5Oiz-xM4V8oT",
    portfolio: "https://ismailaouladtouhami.framer.website/",
    img: "/images/touhami.png",
  },
  {
    name: "FARID Mohamed amine",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=1qvJ8d_bWGePac8COuHX1XWWbOM3hU80F",
    portfolio: "https://medamine31.github.io/mohamed_amine_farid.github.io/",
    img: "/images/Amine.png",
  },
  {
    name: "BAYAT siham",
    spec: "Software Engineer",
    cv: "https://drive.google.com/open?id=1oftaOecg-Y27mmQ36iJy_iNp1vL8C_72",
    portfolio: "https://rerta.my.canva.site/siham-bayat",
    img: "/images/Bayat.jpg",
  },
  {
    name: "TAHIR Youness",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1qxoDvjy2b_kXVBxYppMTLEGkCQRbV6hF",
    portfolio: "https://myportfoliotahir7.my.canva.site/",
    img: "/images/Youness.png",
  },
  {
    name: "Ben Sidi khir Ismail",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1JPjJ9DFVQlI3ok6F5nQ6WHNifX5KqM--",
    portfolio: "https://ismail-bensidi-khir.my.canva.site/",
    img: "/images/touhami_ismail.jpg",
  },
  {
    name: "BOUDLAL Nouhaila",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1AGyq7NsvXhfS74SRwWeuBkKairieovyy",
    portfolio: "https://nouhaila-portfolio.my.canva.site/ ",
    img: "/images/nouhaila_boudlale.jpg",
  },
  {
    name: "GUEDAR Lamiae",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1gIr5rGF5oflPZD2VDGwHD-WOWbyXV7YJ",
    portfolio: "https://portfolio-lamiae-guedar.my.canva.site/",
    img: "/images/lamia_guedar.jpeg",
  },
  {
    name: "OUKALTOUM Ibtissam",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1Kn0YMF0hLjNVXrFeIK2a5ogtgbNWWk3m",
    portfolio: "https://portfolioibtissam.my.canva.site/",
    img: "/images/Ibtissam.jpg",
  },
  {
    name: "Abdou Moussa Abdoul Latif",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1PcJRSnl4zkyk4npEZbXJK85PovREzWv_",
    portfolio: "https://abdoullatif-portfolio.my.canva.site/",
    img: "/images/Moussa.jpg",
  },
  {
    name: "AOUAM El Mehdi",
    spec: "Embeeded System",
    cv: "https://drive.google.com/open?id=1X7Yaq4jAWr983FQoyll6panjWsZYmv0b",
    portfolio: "https://portfolioaouam.my.canva.site/",
    img: "/images/aouam_mehdi.jpg",
  },
  {
    name: "OUABIR chaymae",
    spec: "Market",
    cv: "https://drive.google.com/open?id=1dU5fUo8Ze4NT9j6Ugx8-lr0XJ_iO3GJk",
    portfolio: "",
    img: "/images/oauabir.jpeg",
  },
  {
    name: "MAAZOUZ Wissal",
    spec: "Market",
    cv: "https://drive.google.com/open?id=1CTBxJC5F4Ds5PA8T8xOccmFdIj9Xm39p",
    portfolio: "",
    img: "/images/maazouz.jpeg",
  },
  {
    name: "EL GHAMZOURI Oumaima",
    spec: "Market",
    cv: "https://drive.google.com/open?id=1q4ZNiQZfPoJiuXkn9t9LOFDSXJxw649G",
    portfolio: "",
    img: "/images/ghamzouri.jpg",
  },
  {
    name: "RACHAD Meryem",
    spec: "Market",
    cv: "https://drive.google.com/open?id=12Cyix_RcHYfTKvHhv4B3HAj1e3YPvsO5",
    portfolio: "",
    img: "/images/rachad.jpg",
  },
];
